# Generated by Django 3.1.3 on 2020-11-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alphabet',
            name='is_visible',
        ),
    ]
