# Generated by Django 3.1.3 on 2020-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcatalog', '0002_remove_alphabet_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_assign',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_end',
            field=models.DateField(null=True),
        ),
    ]
